# Generated by Django 3.1.1 on 2020-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=100)),
                ('eventImage', models.ImageField(upload_to='')),
                ('eventDescription', models.CharField(max_length=255)),
                ('eventChifeGuest', models.CharField(max_length=120)),
                ('eventlocation', models.CharField(max_length=150)),
                ('eventStartTime', models.CharField(max_length=25)),
                ('eventDate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobCircular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100)),
                ('jobDescriptio', models.CharField(max_length=255)),
                ('jobPostion', models.CharField(max_length=100)),
                ('jobNuture', models.CharField(max_length=50)),
                ('jobExperiance', models.CharField(max_length=50)),
                ('workPlace', models.CharField(max_length=120)),
                ('educationalRequierments', models.CharField(max_length=150)),
                ('mustRequierdSkills', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('jobImageBanner', models.ImageField(upload_to='')),
                ('deadline', models.CharField(max_length=30)),
            ],
        ),
    ]
