# Generated by Django 3.1.1 on 2020-11-30 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alumni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcircular',
            old_name='jobDescriptio',
            new_name='jobDescription',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=10)),
                ('passingYear', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
