# Generated by Django 3.1.1 on 2020-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0002_auto_20201130_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
