# Generated by Django 3.1.1 on 2020-12-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0003_profile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='eventKeyNote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='eventLink',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='eventImage',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='jobcircular',
            name='jobImageBanner',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
